name: iosApp
options:
  bundleIdPrefix: com.ohyooo.demo
settings:
  base:
    PRODUCT_NAME: iosApp
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      base:
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../ui/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
          - "$(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-framework"
          - "ui"
          - "-framework"
          - "shared"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
    sources:
      - path: iosApp
    info:
      path: iosApp/Info.plist
    preBuildScripts:
      - name: Compile Kotlin
        basedOnDependencyAnalysis: false
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            echo "Skipping Gradle build task invocation due to OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES"
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :ui:embedAndSignAppleFrameworkForXcode
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode
